dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "armannds-github"

node_js:
  - "node"

install:
  - npm install

script:
  - sonar-scanner
  - npm test

cache:
  directories:
  - '$HOME/.sonar/cache'
